name: Longcommon
favicon: null
layout_spectrum: 0.24004225386306643
typography_spectrum: 0.2266089809127152
title: 'Bri Marvich: Florals+ Graphic Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b2b2b2'
    - '#615f60'
    - '#8a8889'
  brandStrength: 0.5
  lightness: 0.4094267867039889
  saturation: 0.9626985376235098
  rhythmicContrast: 0.8730760638136417
purpose: []
